# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gthockey-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gthockey-iOS
  pod 'SwiftLint'
  # pod 'Alamofire', '~> 3.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.0.0-rc.2'

end
