# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gthockey-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gthockey-iOS
  pod 'SwiftLint'
  pod 'RevealingSplashView'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'AlamofireImage'

end
